# Generated by Django 5.2.1 on 2025-05-07 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skillzor", "0003_remove_employeeskill_evidence_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="name",
            new_name="first_name",
        ),
        migrations.AddField(
            model_name="employee",
            name="last_name",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
